# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  vmImageOfBuild: windows-2019
  buildConfiguration: Release
  buildProject: src/WebJobsExtensions.CustomBindings.MicrosoftTeams/WebJobsExtensions.CustomBindings.MicrosoftTeams.csproj
  testProjects: tests/**/*.csproj


stages:
- stage: build
  jobs:
  - job: test_job
    displayName: Test
    pool:
      vmImage: $(vmImageOfBuild)
    steps:
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: $(testProjects)
        testRunTitle: 'run tests'
  - job: pack_job
    displayName: build & pack
    dependsOn:
    - test_job
    condition: and(succeeded('build_job'), succeeded('test_job'))
    pool:
      vmImage: $(vmImageOfBuild)
    steps:
    - task: NuGetCommand@2
      inputs:
        command: pack
        packagesToPack: '$(buildProject)'